// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cache_entry.proto

package org.apache.cassandra.hists;

public final class CacheEntryOuterClass {
  private CacheEntryOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CacheEntryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CacheEntry)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string Keyspace = 1;</code>
     */
    java.lang.String getKeyspace();
    /**
     * <code>optional string Keyspace = 1;</code>
     */
    com.google.protobuf.ByteString
        getKeyspaceBytes();

    /**
     * <code>optional string ColumnFamily = 2;</code>
     */
    java.lang.String getColumnFamily();
    /**
     * <code>optional string ColumnFamily = 2;</code>
     */
    com.google.protobuf.ByteString
        getColumnFamilyBytes();

    /**
     * <code>optional bytes Key = 3;</code>
     */
    com.google.protobuf.ByteString getKey();
  }
  /**
   * Protobuf type {@code CacheEntry}
   */
  public  static final class CacheEntry extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:CacheEntry)
      CacheEntryOrBuilder {
    // Use CacheEntry.newBuilder() to construct.
    private CacheEntry(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private CacheEntry() {
      keyspace_ = "";
      columnFamily_ = "";
      key_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private CacheEntry(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              keyspace_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              columnFamily_ = s;
              break;
            }
            case 26: {

              key_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.apache.cassandra.hists.CacheEntryOuterClass.internal_static_CacheEntry_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.apache.cassandra.hists.CacheEntryOuterClass.internal_static_CacheEntry_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.apache.cassandra.hists.CacheEntryOuterClass.CacheEntry.class, org.apache.cassandra.hists.CacheEntryOuterClass.CacheEntry.Builder.class);
    }

    public static final int KEYSPACE_FIELD_NUMBER = 1;
    private volatile java.lang.Object keyspace_;
    /**
     * <code>optional string Keyspace = 1;</code>
     */
    public java.lang.String getKeyspace() {
      java.lang.Object ref = keyspace_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        keyspace_ = s;
        return s;
      }
    }
    /**
     * <code>optional string Keyspace = 1;</code>
     */
    public com.google.protobuf.ByteString
        getKeyspaceBytes() {
      java.lang.Object ref = keyspace_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        keyspace_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COLUMNFAMILY_FIELD_NUMBER = 2;
    private volatile java.lang.Object columnFamily_;
    /**
     * <code>optional string ColumnFamily = 2;</code>
     */
    public java.lang.String getColumnFamily() {
      java.lang.Object ref = columnFamily_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        columnFamily_ = s;
        return s;
      }
    }
    /**
     * <code>optional string ColumnFamily = 2;</code>
     */
    public com.google.protobuf.ByteString
        getColumnFamilyBytes() {
      java.lang.Object ref = columnFamily_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        columnFamily_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int KEY_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString key_;
    /**
     * <code>optional bytes Key = 3;</code>
     */
    public com.google.protobuf.ByteString getKey() {
      return key_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getKeyspaceBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, keyspace_);
      }
      if (!getColumnFamilyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, columnFamily_);
      }
      if (!key_.isEmpty()) {
        output.writeBytes(3, key_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getKeyspaceBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, keyspace_);
      }
      if (!getColumnFamilyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, columnFamily_);
      }
      if (!key_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, key_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static org.apache.cassandra.hists.CacheEntryOuterClass.CacheEntry parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.apache.cassandra.hists.CacheEntryOuterClass.CacheEntry parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.apache.cassandra.hists.CacheEntryOuterClass.CacheEntry parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.apache.cassandra.hists.CacheEntryOuterClass.CacheEntry parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.apache.cassandra.hists.CacheEntryOuterClass.CacheEntry parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.apache.cassandra.hists.CacheEntryOuterClass.CacheEntry parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.apache.cassandra.hists.CacheEntryOuterClass.CacheEntry parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.apache.cassandra.hists.CacheEntryOuterClass.CacheEntry parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.apache.cassandra.hists.CacheEntryOuterClass.CacheEntry parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.apache.cassandra.hists.CacheEntryOuterClass.CacheEntry parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.apache.cassandra.hists.CacheEntryOuterClass.CacheEntry prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CacheEntry}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CacheEntry)
        org.apache.cassandra.hists.CacheEntryOuterClass.CacheEntryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.apache.cassandra.hists.CacheEntryOuterClass.internal_static_CacheEntry_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.apache.cassandra.hists.CacheEntryOuterClass.internal_static_CacheEntry_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.apache.cassandra.hists.CacheEntryOuterClass.CacheEntry.class, org.apache.cassandra.hists.CacheEntryOuterClass.CacheEntry.Builder.class);
      }

      // Construct using org.apache.cassandra.hists.CacheEntryOuterClass.CacheEntry.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        keyspace_ = "";

        columnFamily_ = "";

        key_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.apache.cassandra.hists.CacheEntryOuterClass.internal_static_CacheEntry_descriptor;
      }

      public org.apache.cassandra.hists.CacheEntryOuterClass.CacheEntry getDefaultInstanceForType() {
        return org.apache.cassandra.hists.CacheEntryOuterClass.CacheEntry.getDefaultInstance();
      }

      public org.apache.cassandra.hists.CacheEntryOuterClass.CacheEntry build() {
        org.apache.cassandra.hists.CacheEntryOuterClass.CacheEntry result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.apache.cassandra.hists.CacheEntryOuterClass.CacheEntry buildPartial() {
        org.apache.cassandra.hists.CacheEntryOuterClass.CacheEntry result = new org.apache.cassandra.hists.CacheEntryOuterClass.CacheEntry(this);
        result.keyspace_ = keyspace_;
        result.columnFamily_ = columnFamily_;
        result.key_ = key_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.apache.cassandra.hists.CacheEntryOuterClass.CacheEntry) {
          return mergeFrom((org.apache.cassandra.hists.CacheEntryOuterClass.CacheEntry)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.apache.cassandra.hists.CacheEntryOuterClass.CacheEntry other) {
        if (other == org.apache.cassandra.hists.CacheEntryOuterClass.CacheEntry.getDefaultInstance()) return this;
        if (!other.getKeyspace().isEmpty()) {
          keyspace_ = other.keyspace_;
          onChanged();
        }
        if (!other.getColumnFamily().isEmpty()) {
          columnFamily_ = other.columnFamily_;
          onChanged();
        }
        if (other.getKey() != com.google.protobuf.ByteString.EMPTY) {
          setKey(other.getKey());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.apache.cassandra.hists.CacheEntryOuterClass.CacheEntry parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.apache.cassandra.hists.CacheEntryOuterClass.CacheEntry) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object keyspace_ = "";
      /**
       * <code>optional string Keyspace = 1;</code>
       */
      public java.lang.String getKeyspace() {
        java.lang.Object ref = keyspace_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          keyspace_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string Keyspace = 1;</code>
       */
      public com.google.protobuf.ByteString
          getKeyspaceBytes() {
        java.lang.Object ref = keyspace_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          keyspace_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string Keyspace = 1;</code>
       */
      public Builder setKeyspace(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        keyspace_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string Keyspace = 1;</code>
       */
      public Builder clearKeyspace() {
        
        keyspace_ = getDefaultInstance().getKeyspace();
        onChanged();
        return this;
      }
      /**
       * <code>optional string Keyspace = 1;</code>
       */
      public Builder setKeyspaceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        keyspace_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object columnFamily_ = "";
      /**
       * <code>optional string ColumnFamily = 2;</code>
       */
      public java.lang.String getColumnFamily() {
        java.lang.Object ref = columnFamily_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          columnFamily_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string ColumnFamily = 2;</code>
       */
      public com.google.protobuf.ByteString
          getColumnFamilyBytes() {
        java.lang.Object ref = columnFamily_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          columnFamily_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string ColumnFamily = 2;</code>
       */
      public Builder setColumnFamily(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        columnFamily_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string ColumnFamily = 2;</code>
       */
      public Builder clearColumnFamily() {
        
        columnFamily_ = getDefaultInstance().getColumnFamily();
        onChanged();
        return this;
      }
      /**
       * <code>optional string ColumnFamily = 2;</code>
       */
      public Builder setColumnFamilyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        columnFamily_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString key_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes Key = 3;</code>
       */
      public com.google.protobuf.ByteString getKey() {
        return key_;
      }
      /**
       * <code>optional bytes Key = 3;</code>
       */
      public Builder setKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        key_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes Key = 3;</code>
       */
      public Builder clearKey() {
        
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:CacheEntry)
    }

    // @@protoc_insertion_point(class_scope:CacheEntry)
    private static final org.apache.cassandra.hists.CacheEntryOuterClass.CacheEntry DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.apache.cassandra.hists.CacheEntryOuterClass.CacheEntry();
    }

    public static org.apache.cassandra.hists.CacheEntryOuterClass.CacheEntry getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CacheEntry>
        PARSER = new com.google.protobuf.AbstractParser<CacheEntry>() {
      public CacheEntry parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CacheEntry(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CacheEntry> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CacheEntry> getParserForType() {
      return PARSER;
    }

    public org.apache.cassandra.hists.CacheEntryOuterClass.CacheEntry getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CacheEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CacheEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021cache_entry.proto\"A\n\nCacheEntry\022\020\n\010Key" +
      "space\030\001 \001(\t\022\024\n\014ColumnFamily\030\002 \001(\t\022\013\n\003Key" +
      "\030\003 \001(\014B\034\n\032org.apache.cassandra.histsb\006pr" +
      "oto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_CacheEntry_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CacheEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_CacheEntry_descriptor,
        new java.lang.String[] { "Keyspace", "ColumnFamily", "Key", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
